version: "3.9"
services:
  pelican:
    build: .
    volumes:
      - ./output:/app/pelican/output
    environment:
      - PARTICIPANTS_RAW_CSV=${PARTICIPANTS_RAW_CSV}
      - PARTICIPANTS_CSV=${PARTICIPANTS_CSV}
      - GDRIVE_DOCUMENT_ID=${GDRIVE_DOCUMENT_ID}
      - GDRIVE_SHEET_ID=${GDRIVE_SHEET_ID}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_MAILING_LIST=${MAILGUN_MAILING_LIST}
