name: Pelican CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build the site
        run: docker-compose run --rm pelican
        env:
          PARTICIPANTS_RAW_CSV: ${{ secrets.PARTICIPANTS_RAW_CSV }}
          PARTICIPANTS_CSV: ${{ secrets.PARTICIPANTS_CSV }}
          GDRIVE_DOCUMENT_ID: ${{ secrets.GDRIVE_DOCUMENT_ID }}
          GDRIVE_SHEET_ID: ${{ secrets.GDRIVE_SHEET_ID }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_MAILING_LIST: ${{ secrets.MAILGUN_MAILING_LIST }}

      # - name: Build EN verison of the site
      #   run: docker-compose -f docker-compose.en.yml run -rm pelican
      #   env:
      #     PARTICIPANTS_RAW_CSV: ${{ secrets.PARTICIPANTS_RAW_CSV }}
      #     PARTICIPANTS_CSV: ${{ secrets.PARTICIPANTS_CSV }}
      #     GDRIVE_DOCUMENT_ID: ${{ secrets.GDRIVE_DOCUMENT_ID }}
      #     GDRIVE_SHEET_ID: ${{ secrets.GDRIVE_SHEET_ID }}
      #     MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      #     MAILGUN_MAILING_LIST: ${{ secrets.MAILGUN_MAILING_LIST }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          cname: vzms.kmm-vsu.ru
